### ISSUE TITLE
Error in gh::gh(...) : GitHub API error (422): 422 Unprocessable Entity   Validation Failed

### ISSUE THREAD

**Issue by jimhester** [jimhester/lookup#15]
This can occur when a repository has been moved to a new user / organization, but was still installed from the old location.

**Comment by gaborcsardi** [comment]
I saw it when I did not use a GH token. After adding the token, the same query worked just fine....

**Comment by jimhester** [comment]
This brings up another point, the response includes a more detailed message, but **gh** does not include it in the condition's message by default.

```r
e <- tryCatch(lookup(dplyr:::select.grouped_df), error = function(e) e)
e$content$errors[[1]]$message
#> [1] "The listed users and repositories cannot be searched either because the res
#> ources do not exist or you do not have permission to view them."
```

It might not be possible to do this, I am not sure if the message location is standardized across the GitHub API.

**Comment by gaborcsardi** [comment]
@jimhester got it.

**Comment by muschellij2** [comment]
Just FYI I have seen this when  using `gh::gh("/user/repos", name="ANYTHING")` when `ANYTHING` already exists.  

I've had it return this in come cases with `usethis::use_github`, but I'm not sure how that could be possible because it checks the remote tree to see if that repo exists first.  

Again, just for someone else who may land here.

It makes sense because it
