### ISSUE TITLE
Fails to lookup functions in purrr

### ISSUE THREAD

**Issue by noamross** [jimhester/lookup#7]
I get an error when lookup up functions in purrr:

```
> library(purrr)
> library(lookup)
> transpose
\
Error in gh::gh(...) : GitHub API error (404): 404 Not Found
  Not Found
```

This seems to have something to do with the fact that, while **purrr** uses Rcpp, it does not have `RcppExports.cpp/R`. Rather, it's user-exposed C functions use the C API, but lower-level functions use the Rcpp C++ library for some things.

**Comment by jimhester** [comment]
Yes, I was aware of this and it is on my local Todo list, should just be a
matter of tweaking the logic a little

On Dec 4, 2016 12:06 PM, "Noam Ross" <notifications@github.com> wrote:

I get an error when lookup up functions in purrr:

> library(purrr)
> library(lookup)
> transpose
\
Error in gh::gh(...) : GitHub API error (404): 404 Not Found
  Not Found

This seems to have something to do with the fact that, while *purrr* uses
Rcpp, it does not have RcppExports.cpp/R. Rather, it's user-exposed C
functions use the C API, but lower-level functions use the Rcpp C++ library
for some things.

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub
<https://github.com/jimhester/lookup/issues/7>, or mute the thread
